spring.application.name=Admin-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:admin_panel_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.sql.init.continue-on-error=true
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true