INSERT IGNORE INTO `activity_logs` (`id`, `action`, `entity_title`, `entity_type`, `status`, `timestamp`, `user`) VALUES
(1, 'Deleted', 'Tech Startup Sharack Expands Mobility Solutions Across Sri Lanka', 'News & Events', 'Completed', '2026-09-07 16:16:34.000000', 'Admin'),
(2, 'Created', 'test', 'News & Events', 'Completed', '2026-09-07 20:09:06.000000', 'Admin'),
(3, 'Updated', '123', 'News & Events', 'Completed', '2026-09-07 20:09:53.000000', 'Admin'),
(4, 'Deleted', '123', 'News & Events', 'Completed', '2026-09-07 20:10:27.000000', 'Admin'),
(5, 'Created', 'test', 'News & Events', 'Completed', '2026-09-07 20:29:31.000000', 'Admin'),
(6, 'Deleted', 'test', 'News & Events', 'Completed', '2026-09-07 20:30:08.000000', 'Admin'),
(7, 'Created', '123', 'News & Events', 'Completed', '2026-09-08 15:44:10.000000', 'Admin'),
(8, 'Deleted', '123', 'News & Events', 'Completed', '2026-09-08 15:45:09.000000', 'Admin'),
(9, 'Created', 'test', 'News & Events', 'Completed', '2026-09-24 08:50:32.000000', 'Admin'),
(10, 'Deleted', 'test', 'News & Events', 'Completed', '2026-09-24 08:50:59.000000', 'Admin');

INSERT IGNORE INTO `government_institutions` (`id`, `cards_json`, `contact_person`, `description`, `region_tag`, `slug`, `title`, `attachment_url`, `thumbnail_url`) VALUES
(3, '', 'Director–DAP', 'Regional partnerships, framework agreements, and collaborative capacity-building initiatives across Asia and the Pacific.', 'HQ Region', 'asia-pacific', 'Asia-Pacific', '', '/uploads/fbc61ddb-ddd4-429b-a016-18bffa0f825c_1.jpg'),
(4, '', 'Director–DAP', 'Intercontinental training programs, policy exchange, and specialized demand reduction networks established with African partner nations.', 'Global Outreach', 'africa', 'Africa', '', '/uploads/81e35eb6-861e-4186-a73b-48812e0aae24_images.jpg');

INSERT IGNORE INTO `individuals_items` (`id`, `badge`, `description`, `link_url`, `section_subtitle`, `section_title`, `slug`, `sort_order`, `thumbnail_url`, `title`) VALUES
(1, 'Archies', 'Explore historical documentation, intergovernmental agreements, and decades of archival reports.', '', 'Self-paced learning on drug prevention, treatment, and recovery curricula — open to professionals, practitioners, and anyone.', 'DAP e-learning platform', 'archives', 1, '/uploads/ea635cf5-ef99-41cb-9c71-3d83867cf09a_1.jpg', 'Access archival records for research purposes'),
(2, 'E-Learning', 'Self-paced learning on drug prevention, treatment, and recovery curricula — open to professionals, practitioners, and anyone.', '', 'Self-paced learning on drug prevention, treatment, and recovery curricula — open to professionals, practitioners, and anyone.', 'DAP e-learning platform', 'courses', 0, '/uploads/641afdd4-7fe4-4baa-bb8b-8b62aeada038_2.jpg', 'Browse Courses');

INSERT IGNORE INTO `member_portal_items` (`id`, `badge`, `bullet_points`, `description`, `link_url`, `page_description`, `page_tag`, `page_title`, `slug`, `sort_order`, `thumbnail_url`, `title`) VALUES
(1, 'PUBLIC RESOURCE', 'Upcoming regional workshops & schedules\nParticipant certification archives\nExpert-led instructional modules', 'Explore upcoming capacity-building workshops, professional short courses, and specialized technical modules. View recently concluded sessions along with certified participant names and institutional profiles.', '', 'Access exclusive regional development resources, specialized training programmes, long-term scholarship archives, and official committee documentation designed to empower sovereign member states across Asia and the Pacific.', 'REGIONAL COOPERATION & DEVELOPMENT HUB', 'Member Countries Portal', 'training-opportunities', 0, '/uploads/aa2d355e-c1d5-4f28-a972-bae5036f7b49_1.jpg', 'Training Opportunities'),
(2, 'PUBLIC RESOURCE', 'Master\'s & doctoral degree opportunities\nApplication guidelines & criteria\nDirectory of alumni & past awardees', 'Discover full-funding academic scholarships, postgraduate programs, and fellowship grants offered in collaboration with premier regional universities. Browse past awardees and institutional success records.', '', 'Access exclusive regional development resources, specialized training programmes, long-term scholarship archives, and official committee documentation designed to empower sovereign member states across Asia and the Pacific.', 'REGIONAL COOPERATION & DEVELOPMENT HUB', 'Member Countries Portal', 'long-term-scholarships', 1, '/uploads/2ec7e3da-be75-4880-b66a-074d5f84ad00_2.jpg', 'Long-Term Scholarships'),
(3, 'MEMBERS ONLY', 'Quarterly council proceedings & minutes\nConfidential policy review documents\nMember state delegate archives', 'Restricted portal for official delegates. Access meeting agendas, working documents, executive decisions, and policy records of the Consultative Committee (CCM) and Executive Committee (EPG).', '', 'Access exclusive regional development resources, specialized training programmes, long-term scholarship archives, and official committee documentation designed to empower sovereign member states across Asia and the Pacific.', 'REGIONAL COOPERATION & DEVELOPMENT HUB', 'Member Countries Portal', 'council-standing-committee-meetings', 2, '/uploads/5b1bf0ff-c15c-400a-9256-a631072ae829_3.jpg', 'Council & Standing Committee Meetings');

INSERT IGNORE INTO `news_events` (`id`, `author`, `category`, `content`, `description`, `event_date`, `image_alt`, `image_url`, `location`, `publish_date`, `slug`, `status`, `title`, `file_name`, `file_url`) VALUES
(5, 'Secretariat', 'Event', '', 'Regional delegates and health specialists convened to present updated evidence-based prevention toolkits and cross-border cooperation frameworks.', '', '', '/uploads/92015749-15dd-4fb1-a17b-1baed8dcc27c_Annual_Capacity.jpg', '', '2026-09-12', 'annual-capacity-building-drug-advisory-summit', 'Published', 'Annual Capacity Building & Drug Advisory Summit', '', ''),
(6, 'Secretariat', 'News', '', 'The Colombo Plan Secretariat published comprehensive statistical reviews detailing human resource investments across 26 member countries.', '', '', '/uploads/41eb5f5c-458c-4005-9820-293291822361_Publication_Release.jpg', '', '2026-09-03', 'publication-release-2026-south-south-cooperation-index', 'Published', 'Publication Release: 2026 South-South Cooperation Index', '', ''),
(7, 'Secretariat', 'News', '', 'Official launch of digital skill accreditation courses for young professionals and civil society leaders across the Asia-Pacific region.', '', '', '/uploads/5c59376d-6f69-4455-ba9f-7c1a6943246a_Youth_and_Gender.jpg', '', '2026-09-18', 'youth-gender-empowerment-initiative-launch', 'Published', 'Youth & Gender Empowerment Initiative Launch', '', '');

INSERT IGNORE INTO `private_sector_content` (`id`, `csr_partnerships`, `description`, `focal_point`, `region_tag`, `slug`, `thumbnail_url`, `title`, `what_we_offer`) VALUES
(3, 'Independent, delivery-focused implementation', 'Workforce upskilling, partnerships and CSR opportunities', 'Pulsara G', '', 'private-sector', '', 'PRIVATE SECTOR', 'Global Network of Trainers — certified specialists across partner countries\nEvidence-Based Prevention Curricula — workplace, youth, community, family\nWomen, Youth & Community Programmes — empowerment and inclusive capacity building\nCorporate Prevention Programmes — tailored substance use risk management for workforces\nAfrican Network Partnerships — expanding collaborative prevention frameworks across Africa\nDigital Prevention & E-Learning Modules — accessible online training platforms for remote stakeholder capacity building');

INSERT IGNORE INTO `programs` (`id`, `description`, `image_url`, `title`, `category_badge`, `established_info`, `feature_cards_json`, `feature_section_title`, `full_description`, `hero_image_url`, `impact_badges_json`, `impact_description`, `impact_title`, `portal_button_text`, `portal_url`, `short_code`, `slug`, `brochure_url`, `initiatives_json`, `initiatives_section_title`, `partnership_label`, `partnership_stats_json`, `partnership_title`, `theme_color`) VALUES
(5, 'Pioneering regional efforts in evidence-based substance use prevention, treatment practitioner certifications, and community recovery networks active across 80+ countries globally. Established in 1973, setting international standards through the Universal Treatment Curriculum (UTC).', '/uploads/e2f28d65-626d-4ca1-aec3-6cd17f9d8af9_DAP.jpg', 'Drug Advisory Programme (DAP)', 'Flagship Programme', '', '[{\"title\":\"Curricula Development & Training\",\"description\":\"Developing and implementing the Universal Treatment Curriculum (UTC) for addiction professionals to set high international standards in counselling and treatment.\"},{\"title\":\"Curriculum-Based Training\",\"description\":\"Conducting specialized training cycles for regional practitioners, law enforcement, and healthcare workers to manage substance use prevention effectively.\"},{\"title\":\"Donor-Directed Special Interventions\",\"description\":\"Executing targeted projects funded by international partners focusing on vulnerable communities, youth protection, and gender-responsive care.\"},{\"title\":\"Accreditation of Training Providers\",\"description\":\"Verifying and certifying regional training institutions and professionals through rigorous credentialing boards to maintain global quality benchmarks.\"}]', 'Drug Demand Reduction (DDR)', 'Established in 1973, DAP is the Colombo Plan\'s premier flagship initiative. It sets international standards for addiction treatment professionals through the Universal Treatment Curriculum (UTC) and supports national policy frameworks.', '/uploads/c9cc4b6c-ef81-4505-ae31-1e2609b1c3b6_DAP.JPG', '[]', 'Through decades of commitment, DAP has successfully certified thousands of addiction treatment and prevention professionals across Asia, Africa, and the Americas. By introducing standardized curricula and fostering regional peer networks, DAP continues to lead global efforts in mitigating substance use disorders.', 'Global Impact & Professional Standards', '', '', 'DAP', 'drug-advisory-programme-dap', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'Advancing human resource development through specialized technical training, professional certifications, and prestigious master’s degree scholarships for member state officials, bridging critical public and private sector skill gaps.', '/uploads/3290e2e5-86dc-4e84-a3dc-4854c90497ff_CBP.jpg', 'Capacity Building Programme (CBP)', 'EDUCATION & SKILLS', 'CAPACITY BUILDING & SCHOLARSHIPS', '[{\"title\":\"Public Administration & Governance\",\"description\":\"Empowering civil servants, policymakers, and public sector administrators with advanced governance models, transparency frameworks, and policy implementation strategies.\"},{\"title\":\"Master\'s Degree Scholarships\",\"description\":\"Offering fully funded long-term postgraduate scholarships in partnership with top-tier universities across member nations to cultivate future regional leaders.\"},{\"title\":\"TVET & Technical Upskilling\",\"description\":\"Bridging industrial skill gaps through Technical and Vocational Education and Training (TVET) modules tailored for modern technological demands.\"},{\"title\":\"South-South Knowledge Exchange\",\"description\":\"Facilitating cross-border peer learning, expert delegations, and sharing best practices among developing member economies.\"}]', 'Strategic Priorities & Focus Areas', 'Focuses on bridging public sector skill gaps, fostering administrative excellence, and offering long-term academic scholarships in partnership with top-tier regional universities and institutions.', '/uploads/87cc704a-e748-4d7b-b66c-c7a2c01f5b99_CBP.jpg', '[]', 'CBP nominations are channeled directly through national focal points and government ministries of member states. Selected candidates undergo rigorous training modules, gaining internationally recognized certifications and practical expertise to implement institutional reforms upon return.', 'Programme Impact & Nomination Guidelines', '', '', 'CBP', 'capacity-building-programme-cbp', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'Promoting sustainable green growth, renewable energy adoption, climate resilience projects, and green economy policies across vulnerable Asia-Pacific regions, supporting environmental ministries and carbon footprint mitigation.', '/uploads/adc12c11-f42c-45fc-b4cd-7b280df39330_CPECC.jpg', 'Environment & Climate Change (CPECC)', 'SUSTAINABILITY', 'CLIMATE ADAPTATION & GREEN ECONOMY', '[{\"title\":\"Solid Waste & Plastic Management\",\"description\":\"Promoting circular economy solutions, municipal waste reduction frameworks, and advanced recycling technologies across developing urban centers in the region.\"},{\"title\":\"Renewable Energy & Clean Tech\",\"description\":\"Capacity building on solar, wind, and geothermal adoption, supporting national grids in transitioning away from fossil fuel dependencies.\"},{\"title\":\"Sustainable Eco-Tourism\",\"description\":\"Developing nature-positive tourism standards that empower local indigenous communities while conserving fragile forest and coastal ecosystems.\"},{\"title\":\"Climate Resilience & Adaptation\",\"description\":\"Disaster risk mitigation training, early-warning system integration, and community-driven adaptation policies for vulnerable island and coastal states.\"}]', 'Strategic Priorities & Focus Areas', 'Aids developing member countries in formulating climate adaptation strategies, mitigating environmental degradation, and sharing green technology best practices through South-South cooperation.', '/uploads/6fb23164-4675-4d56-be23-e4fdc0d25446_ASEAN Biodiversity Center Collaboration.jpg', '[]', 'CPECC aligns its regional agendas directly with UN Sustainable Development Goals (SDGs 7, 13, and 15), facilitating cross-border partnerships that protect biodiversity and accelerate clean energy transitions.', 'Commitment to Sustainable Development Goals (SDGs)', '', '', 'CPECC', 'environment-climate-change-cpecc', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'Strengthening maritime safety, port infrastructure development, technical advisory, and regional logistics cooperation across strategic shipping corridors through active pilot initiatives with regional port authorities.', '/uploads/516ea7a5-cfca-4c78-bf92-5a9e9617fbbb_MAP.jpg', 'Maritime Advisory Programme (MAP)', 'LOGISTICS & SAFETY', 'MARITIME SECURITY & TRADE', '[{\"title\":\"SLPA Capacity Building\",\"description\":\"Technical advisory visits, specialized port personnel training, and global best-practice knowledge exchange frameworks.\"},{\"title\":\"Digital Port Transformation\",\"description\":\"Advancing maritime cybersecurity, workforce digital readiness, IoT port connectivity, and paperless logistics systems.\"},{\"title\":\"Port Security & Safety\",\"description\":\"Enhancing ISPS compliance, physical container terminal security protocols, and marine emergency response protocols.\"},{\"title\":\"Regional Logistics Connectivity\",\"description\":\"Strengthening Indian Ocean transshipment networks and sustainable green shipping corridor initiatives.\"}]', 'Current Focus Areas & Pillars', 'Addresses vital maritime security challenges, enhances regulatory compliance for port management, and facilitates seamless cross-border maritime trade frameworks among coastal member states.', '/uploads/aa6e24e5-accf-4fab-b93f-607443b6d6df_MAP.jpg', '[]', 'MAP aims to establish standardized benchmarks for port administration across the Asia-Pacific. By fusing technical advisory with cutting-edge cybersecurity and sustainable green logistics, MAP ensures that participating ports remain resilient against future global supply chain disruptions.', 'Long-Term Regional Maritime Objectives', '', '', 'MAP', 'maritime-advisory-programme-map', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT IGNORE INTO `publications` (`id`, `file_url`, `title`, `description`, `image_url`, `author`, `category`, `file_name`, `publish_date`, `status`) VALUES
(3, '', 'The Colombo Plan Annual Report 2025/2026', 'Comprehensive overview of strategic advancements, human resource development milestones, and regional cooperation outcomes.', '/uploads/9ced02e7-0607-4545-8832-14734574d095_01.jpg', 'The Colombo Plan Secretariat', 'Report', '', '2026-08-01', 'Published'),
(4, '', 'Drug Advisory Programme Impact Assessment', 'Evaluation metrics on practitioner certifications, treatment methodologies, and community substance use prevention.', '/uploads/2628dfc2-269d-4f46-871d-22a0fd2ceeb2_2.jpg', 'Drug Advisory Programme', 'Report', '', '2026-07-01', 'Published'),
(5, '', 'Project Imprint Series', 'Comprehensive documentation tracking technical assistance projects and implementation progress across member nations.', '/uploads/c43f946f-efaf-4f8d-8bd0-1b3161132ad8_3.jpg', 'Research & Technical Division', 'Document', '', '2026-06-01', 'Published'),
(6, '', 'CCM Reports', 'Quarterly proceedings, policy review documentation, and consultative committee decisions.', '/uploads/1822daaf-ad2d-4335-81b8-44554deac5cb_4.jpg', 'Consultative Committee', 'Report', '', '2026-05-01', 'Published');